format_version: 10
pipelines:
  Project-demo-pipeline:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-2ca2e60:
        git: https://github.com/PdskDev/jenkins-tuto-app.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - Compile:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          Install-deps:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - install
                command: npm
                run_if: passed
            - exec:
                arguments:
                - test
                command: npm
                run_if: passed
